### PR TITLE
Support public browser

### LINKED ISSUE #15: Public browser listing shows the server but we arent able to connect.
The server now shows in public browser, however, when attempting to connect through the public browser you will get an error, the  server is available on the web and allows inbound connections when connecting to the ip directly. This is due to the fact the outbound ports are randomized and because the server needs to reach out to update the browser with connection details and keepalive state on port 34197. 

This is better explained by this writeup on [serverfault](https://serverfault.com/questions/1067199/routing-inbound-and-outbound-udp-traffic-to-the-same-port-in-kubernetes?newreg=227d674135a646f39cb9e70ab1e29f92); 

If anyone has any ideas on how we can look to resolve this I would be happy to implement them.

### PR DESCRIPTION
**Pull request by ZCube**
* Fix #15 
* Add Port config
* Add HostNetwork Option (default true)
* Add readiness probe (local mode factorio-port-fixer needed)
* Add factorio-port-fixer as sidecar (optional)

* ⚠️  Warning : hostnetwork will not works well on docker-desktop (windows or mac)
* ⚠️  Warning : factorio-port-fixer is not required unless it is a public game.

### CODE REVIEW

**Comment by SQLJames** [comment]
This looks awesome I am excited to test this one.
Can you make it so the value specified for the port in the values.yaml is persisted through the deployment.yaml? Right now they are just hard coded in the deployment.yaml

**Comment by ZCube** [comment]
The 34197 port set for the pingpong server is fixed in the factorio server executable file and cannot be modified. (ex: pingpong1.factorio.com)

**Comment by SQLJames** [comment]
It was the remote port on the factorio fixer.

**Comment by ZCube** [comment]
Fixed.

**Comment by ZCube** [comment]
This PR needs more time to test.

**Comment by SQLJames** [comment]
Understood, let me know if you need someone to bounce ideas off of.

**Comment by ZCube** [comment]
I actually made the game and succeeded in accessing it. Normal network operation did not work because HostNetwork crashed.
There seems to be some breaking change. 34197 port unavailable, and limited lan search feature due to hostnetwork unavailability.
I plan to keep the server open for testing today. (server name: factorio)

**Comment by ZCube** [comment]
If you want to install this feature without restrictions, you should use factorio-port-fixer on a remote mode server. However, since this requires an external resource (someone else's), I would like to avoid it if possible.
```
hostAliases:
  - ip: "144.24.94.63"
    hostnames:
    - "pingpong"
    - "pingpong1.factorio.com"
    - "pingpong2.factorio.com"
    - "pingpong3.factorio.com"
    - "pingpong4.factorio.com"
```

**Comment by SQLJames** [comment]
It looks like I was able to access your game, though im not sure what the sidecar seems to be doing in this deployment. Would you mind explaining what is happening here? Also, it looks like we are just pointing the pingpong servers to localhost, should that be changed? I guess I am a bit lost on what is happening with this change to begin with haha.

As for the host networking, that might be related to the comment I have about UDP ports for kubernetes, its dated but it is why the game was originally running on port 30000 later changed to 31497. In your PR you accidently replaced this along the way so it crashes when I tried to deploy it with your values.

**Review by SQLJames — CHANGES_REQUESTED** [review]
See previous comment, also author asked for more time to deal with potential issues.

**Comment by ZCube** [comment]
Basically, the sidecar does two things.
1. Change the matching ip and port of factorio to the desired values.
2. Provides /health api to check if factorio is running. (using pingpong packets)

We need to fix the pingpong address to the factorio server in order to implement feature 1.

In k8s, only fixed IPs in hostaliases can be used, so I selected a sidecar that operates on the same network. (localhost available)



I know that these Pull Requests can be complex. I would like to think of it as an option.

If you want a way to operate while maintaining all existing features. You will need a factorio-port-fixer server running in remote mode. This is not recommended for reasons such as privacy and server cost. I'm maintaining one as a sample on Oracle Cloud.

**Comment by ZCube** [comment]
I'm closing this PR because I think it's way too hacky.

**Comment by SQLJames** [comment]
Understood, I am still stepping through this here and there to see how we can move forward based on your work

**Comment by ZCube** [comment]
If it's based on docker-compose, it's much simpler.
```
version: '3.5'

services:
  pingpong:
    image: ghcr.io/zcube/factorio-port-fixer
    command: /factorio-port-fixer local --ip=0.0.0.0 --port=34197 --remotePort=${PORT:-34197}
    restart: unless-stopped
    environment:
      - PORT=${PORT:-34197}
      
  factorio:
    image: factoriotools/factorio
    restart: unless-stopped
    environment:
      - PORT=${PORT:-34197}
      - TZ=UTC
    ports:
     - "${PORT:-34197}:${PORT:-34197}/udp"
     - "27015:27015/tcp"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./factorio:/factorio
    links:
      - 'pingpong:pingpong1.factorio.com'
      - 'pingpong:pingpong2.factorio.com'
      - 'pingpong:pingpong3.factorio.com'
      - 'pingpong:pingpong4.factorio.com'
```

**Pull request closed without merging**
