### PR TITLE
[Proposed change] Added the configuration to run the Space Exploration mod

### PR DESCRIPTION
**Pull request by Vanderscycle**
Hey,

This PR adds an example folder for large mods `values.yaml`. Currently the only one is about [`space-exploration`](https://mods.factorio.com/mod/space-exploration)

### CODE REVIEW

**Comment by SQLJames** [comment]
I definitely agree and like the idea of us presenting a example deployment however I do have some concerns about configuration drift in our repository.  

If we want to go this route, I think we should only reference the mod list and the changes for the server-gen-settings and map-generation. similar to what I added to the [readme](https://github.com/SQLJames/factorio-server-charts/blob/main/charts/factorio-server-charts/README.md#space-exploration-and-other-overhaul-mods). This way most of the defaults are just maintained from the values file.  I do also believe this would be better conveyed through a walkthrough deployment in a markdown instead of a values file, so they are better equipped to debug if needed. Thoughts?

**Comment by SQLJames** [comment]
As an additional note, if we are going to move through with maintaining some of these configurations. These are the mods I think we should target first.

- krastorio
- bob and angels 
- seablock 
- space ex

**Comment by proegssilb** [comment]
From a documentation perspective, I like how this conversation is going.

I wonder if there's any interest in some kind of automated testing to make sure proposed changes don't break the ability to run the game in a battery of common scenarios?

Not saying this repo is at the scale where it's necessary, or that there'd be more benefit than cost. Just asking the question.

**Comment by SQLJames** [comment]
> I wonder if there's any interest in some kind of automated testing to make sure proposed changes don't break the ability to run the game in a battery of common scenarios?
> Not saying this repo is at the scale where it's necessary, or that there'd be more benefit than cost. Just asking the question.

I would be interested in getting this together and working with you on this as its something we would need as this repo gets more traction. Would you mind moving this topic to a discussion, We can further talk about the idea behind automating deployments and then when we have a list of some functionality behind it we can create a branch to work on it.

**Comment by SQLJames** [comment]
> In this case, we could just have a readme for each with the required mods + tweaks required to make the values.yaml work.
Yeah, I agree this would likely be the best choice, do you want to rework the PR? If we put together some automated testing i think we will likely need to rework this idea again, but for a first crack I'd rather a more verbose approach instead.

**Comment by proegssilb** [comment]
> Would you mind moving this topic to a discussion, We can further talk about the idea behind automating deployments and then when we have a list of some functionality behind it we can create a branch to work on it.

Definitely. I was just thinking some of the work done here might be useful for that. But we'll talk more elsewhere.

**Comment by Vanderscycle** [comment]
> Yeah, I agree this would likely be the best choice, do you want to rework the PR? If we put together some automated testing i think we will likely need to rework this idea again, but for a first crack I'd rather a more verbose approach instead.

By automated testing what CICD github action are you thinking? I was thinking a CI step, when a  PR is opened, to test the chart if changes are made to the chart itself.

**Pull request merged**
