### PR TITLE
add container env 'DLC_SPACE_AGE' support

### LINKED ISSUE #51: Add option to disable Space Age DLC
https://github.com/factoriotools/factorio-docker/pull/519

new env `DLC_SPACE_AGE` is now available.

### PR DESCRIPTION
**Pull request by Kariton**
fixes #51 

rebase / version bump follows when #50 is merged.

### CODE REVIEW

**Comment by Kariton** [comment]
was unsure what you would prefer - the "technical" term or the "human" version.
e.g.: `DLC_SPACE_AGE` / `enable_space_age`

also updated the comments to match those from the container repo.

**Comment by Fank** [comment]
I went for `DLC_SPACE_AGE` because the environment scope is quite limited for naming, and since its a DLC i went for DLC prefix.
But here i would recommend using enable as prefix, its easier to understand.

**Review by SQLJames — APPROVED** [review]

**Comment by SQLJames** [comment]
pending merger for #50 Because we will need to bump the chart version to 2.0.1 here.

**Comment by Kariton** [comment]
lol.

this time my own run failed the first time.
second time worked...

https://github.com/Kariton/factorio-server-charts/actions/runs/11477874206/job/31941033773

**Comment by Kariton** [comment]
something odd is happening with the GH workflow

**Comment by Kariton** [comment]
your chart release GH token seems to be expired. ;)

**Review by SQLJames — APPROVED** [review]

**Comment by SQLJames** [comment]
its fixed now and merged in, still getting weird instances of that rcon port but ill dig into that likely this weekend and maybe add more tests as well.

**Pull request merged**
