### PR TITLE
Space age values

### PR DESCRIPTION
**Pull request by Kariton**
fixes: #48

### CODE REVIEW

**Comment by Kariton** [comment]
Changes based of: https://github.com/wube/factorio-data/compare/1.1.110...2.0.8

**Comment by Kariton** [comment]
I havent commented all `@param` values because i cant find any resources on them ATM

**Review by SQLJames — APPROVED** [review]

**Comment by SQLJames** [comment]
I believe the lint error for versions is not a str in the ci is related to the version in chart.yaml I believe it should be 2.0.0 not 2.0

**Comment by Kariton** [comment]
hm.
server startet but still "rcon connection refused"
> 1.191 Info CommandLineMultiplayer.cpp:288: Maximum segment size = 100; minimum segment size = 25; maximum-segment-size peer count = 10; minimum-segment-size peer count = 20

dunno how i can debug / help here...

**Comment by SQLJames** [comment]
Based on what I can see the rcon port is 27015 but the test that it is running is trying to hit 30100

I am assuming they changed the file for the rcon configuration as well. 

```
/bin/sh
      -ec
      RCONPW="$(cat /rconpw/rconpw)"
      ./rcon -a factorio-server-charts-n9ekxcwrpb-rcon:30100 -p $RCONPW -t rcon -T 180s /s Test
 ```

**Comment by Kariton** [comment]
works on my machine. 🥇 

```sh
# nc -v 172.19.11.1 30100
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Connected to 172.19.11.1:30100.
```
log:
> 3715.829 Info RemoteCommandProcessor.cpp:248: New RCON connection from IP ADDR:({X.X:X:X:34954})

my rcon config is basically the values.yml default.
```yaml
rcon:
  external: true
  type: LoadBalancer
  port: 30100
  passwordSecret: factorio-rcon-password
  ```
only updated whats within this PR...

```sh
# k get svc factorio-server-factorio-server-charts-rcon
NAME                                          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
factorio-server-factorio-server-charts-rcon   LoadBalancer   10.42.159.241   172.19.11.1   30100:31365/TCP   74m
```
```sh
# k describe svc factorio-server-factorio-server-charts-rcon
Name:                     factorio-server-factorio-server-charts-rcon
Namespace:                factorio
Labels:                   app=factorio-server-factorio-server-charts
                          app.kubernetes.io/managed-by=Helm
                          chart=factorio-server-charts-1.2.5
                          heritage=Helm
                          release=factorio-server
Annotations:              field.cattle.io/publicEndpoints:
                            [{"addresses":["172.19.11.1"],"port":30100,"protocol":"TCP","serviceName":"factorio:factorio-server-factorio-server-charts-rcon","allNodes...
                          meta.helm.sh/release-name: factorio-server
                          meta.helm.sh/release-namespace: factorio
Selector:                 app=factorio-server-factorio-server-charts
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.42.159.241
IPs:                      10.42.159.241
LoadBalancer Ingress:     172.19.11.1
Port:                     rcon  30100/TCP
TargetPort:               27015/TCP
NodePort:                 rcon  31365/TCP
Endpoints:                10.41.4.47:27015
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

ill see what i can find later. it got early today. :)

**Comment by Kariton** [comment]
it actually worked for me.... pipeline succeeded.

see: https://github.com/Kariton/factorio-server-charts/pull/1

can you please rerun yours?

**Comment by SQLJames** [comment]
Very strange, I ran it twice and first time it failed second time it worked.

**Comment by zwolsman** [comment]
Release seems to fail on the `main` branch now, could you run it again? 😛

**Comment by SQLJames** [comment]
needed to update the pat for publishing releases its there now.

**Pull request merged**
